import React, { FC } from "react";
import type { Metadata } from "next";
import { Folder } from "@/components/Folder/Folder";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Contact-me",
  description: "Generated by ilkay",
};

interface InfoLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<InfoLayoutProps> = ({ children }) => {
  const contactsData = [
    {
      title: "ilkayalti@hotmail.com",
      href: "ilkayalti@hotmail.com",
      icon: "/mailIcon.svg",
    },
    {
      title: "+905555555555",
      href: "905555555555",
      icon: "/phoneIcon.svg",
    },
  ];

  const findMeAlsoData = [
    {
      title: "YouTube channel",
      href: "ilkayalti@hotmail.com",
      icon: "/linkIcon.svg",
    },
    {
      title: "Twich profile",
      href: "905555555555",
      icon: "/linkIcon.svg",
    },
  ];

  return (
    <div className="flex h-full">
      <div className="flex flex-col w-1/4 h-full  border-r border-[#1E2D3D]">
        <Folder folderTitle="contacts" image="down" data={contactsData} />
        <Folder
          folderTitle="find-me-also-in"
          image="down"
          data={findMeAlsoData}
        />
      </div>
      <div className="flex-grow">{children}</div>
    </div>
  );
};

export default RootLayout;
