import React, { FC } from "react";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header";
import FooterComponent from "@/components/Footer";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2024 Portfolio Project",
  description: "Generated by ilkay",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={(firaCode.className, `flex flex-col h-screen`)}>
        <HeaderComponent />
        <div className="flex-1">{children}</div>
        <FooterComponent />
      </body>
    </html>
  );
};

export default RootLayout;
