import React, { FC } from "react";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header";
import FooterComponent from "@/components/Footer";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2024 Portfolio Project",
  description: "Generated by ilkay",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={
          (firaCode.className,
          `flex flex-col h-screen bg-[#01080E] p-8 text-white `)
        }
      >
        <div className="flex flex-col h-screen bg-[#011627] rounded-3xl border border-[#1E2D3D]">
          <HeaderComponent />
          <div className="flex-grow">{children}</div>
          <FooterComponent />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
